spring.application.name=NewStudent


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#databaseconfiguration
#spring.datasource.url=jdbc:mysql://pjsofttech-db-2.cri6eu8uc7zv.ap-south-1.rds.amazonaws.com:3306/student?ServerTimezone=UTC
#spring.datasource.username=admin
#spring.datasource.password=pjsofttechAWS
#server.port:54443
#server.ssl.key-store=/etc/letsencrypt/live/pjsofttech.in/pjsofttech.p12
#server.ssl.key-store-password=123456
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=pjsofttech.in
#server.ssl.enabled=true
#client.superadmin.base-url=https://pjsofttech.in:43443

#razorpay.key.id=rzp_live_MqXuTcHOBV3WID
#razorpay.key.secret=rq645vCHdXcJAw76mzLHiOo6

razorpay.key.id=rzp_test_SsPDymlj4HHUZO
razorpay.key.secret=YOaJxIRpQa5tY0CYgvt4ZJul

#
spring.datasource.url=jdbc:mysql://localhost:3306/layerstudent?ServerTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pikachu@24680
server.port=8111
client.superadmin.base-url=http://localhost:8106


# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Email validation
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=info.pjsofttech@gmail.com

spring.mail.password=wtok telq zpaj dzhg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# AWS S3 Configuration
aws.access-key=AKIA33IBOOI4K6F6U4DJ
aws.secret-key=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
aws.s3.bucket-name=attendace-docs
aws.region=ap-south-1

spring.jackson.date-format=yyyy-MM-dd
spring.jackson.serialization.write-dates-as-timestamps=false

## JWT Secret Key and Expiration Time
jwt.secret=s3cR3tK3y!@#4567890qwertyuiopasdfgh
jwt.expiration=10800000

spring.output.ansi.enabled=ALWAYS